default: &default
  adapter: postgresql
  encoding: unicode
  username: postgres      # <-- your DB username
  password: admin              # <-- optional if no password
  host: localhost

development:
  <<: *default
  database: your_app_development

test:
  <<: *default
  database: your_app_test

production:
  <<: *default
  database: your_app_production
  username: your_app
  password: admin
